server:
  port: 8001
zuul:
  routes:
    demo:
      path: /demo-filter
spring:
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka